### ISSUE TITLE
 AYH-3: Spin up services for Health app

### ISSUE THREAD

**Issue by nJim** [yalesites-org/ask-yale-health#3]
Story: As testers, we need to have access to a sandbox where we can test this app while it is being developed to identify and issues early and provide meaningful feedback.

## Description of work

- Create a new vector database and web service to power the AskYale Health chat app.
- Seed any data into the database so we can verify it is working. Yale Health data injestion will take place in a future ticket.
- Deploy a new Azure AI Studio using the new resource.
- Set permissions so that our core team can test this app on the Azure-hosted web interface.
- Any new services should use the existing resource group to ensure everyone has the correct permissions.

## Acceptance criteria

- [ ] Sebastian, April, Emma, Emily, and Franz can access the web interface.
- [ ] Information about these services is shared to the team via Teams. (Omit any security keys/etc.)

**Comment by alan-scrimenti** [comment]
askyalehealth web app is active and ready for review

https://askyalehealth.azurewebsites.net/
 
The index is called askyalehealth and only contains the text version page (node 1). https://test-ys-yalehealth-ask-yale-edu.pantheonsite.io/summary-of-benefits-and-coverage/text-only-clerical-technical-service-maintenance-security
 
Here is the configuration:
{"systemPrompt":"You are an AI assistant that helps people find information.","fewShotExamples":[],"chatParameters":{"deploymentName":"regression35","maxResponseLength":2000,"temperature":0.2,"topProbablities":1,"stopSequences":null,"pastMessagesToInclude":10,"frequencyPenalty":0,"presencePenalty":0}}
 
Here is the Web App:
https://portal.azure.com/#@yale.edu/resource/subscriptions/fad6ea24-7b90-47c7-8a8e-5931f469931f/resourceGroups/subscription-ai-eastus2-rg/providers/Microsoft.Web/sites/askYaleHealth/appServices

**Comment by nJim** [comment]
App is there and all services are running. Marking this task as complete.
