### ISSUE TITLE
Establish space for internal developer docs

### ISSUE THREAD

**Issue by nJim** [yalesites-org/ask-yale-health#5]
Story: As as developer, I need a space that describes the technical services used in this project, so that I can quickly get up to speed. 

## Description of work

- Create a space where our team can share documentation. This should use a Yale approved technology such as a Teams doc or in Atlassian's wiki.
- Describe how someone can get access to the project.
- Include details about what services are being used and any background information for using this portal.

## Acceptance criteria

- [ ] Documentation is available in a space that is available to our dev-team.

**Comment by alan-scrimenti** [comment]
In the Teams "AI at Yale", "Ask.Yale.Edu" channel there is a Files folder "Project Document" created by Megan that looks like a good place for the related docs. If you would like it somewhere else, let me know.

I created a "Microsoft Azure Resources" document that contains links and information about the Azure platform as it relates to our askYale resources.

**Comment by nJim** [comment]
Perfect. I think this will help others join the project and find their way around Azure-land.
